---
title: "NBA player salary prediction"
output: github_document
---

```{r}
nba = read.csv("nba_data_raw.csv")
nba = na.omit(nba)
nba = subset(nba, select=-c(Player))
```


### Linear Regression Model(train:test = 0.8:0.2)

#### Forward

```{r}
library(leaps)
set.seed(1)

train=sample(c(TRUE, FALSE), nrow(nba), replace=TRUE, prob=c(0.8,0.2))
test=(!train)
regfit.best = regsubsets(Total_salary~., data=nba[train,], nvmax=47,method='forward')
test.mat = model.matrix(Total_salary~., data=nba[test,])
val.errors=rep(NA,47)
for (i in 1:47){
  coefi=coef(regfit.best, id=i)
  pred=test.mat[,names(coefi)]%*%coefi
  val.errors[i]=sqrt(mean((nba$Total_salary[test]-pred)^2))
}
print(paste("Test Dataset Minimum RMSE:", round(min(val.errors),2)))
coef(regfit.best ,which.min(val.errors))
```


#### Backward

```{r}
library(leaps)
set.seed(1)
train=sample(c(TRUE, FALSE), nrow(nba), replace=TRUE, prob=c(0.8,0.2))
test=(!train)
regfit.best = regsubsets(Total_salary~., data=nba[train,], nvmax=47,method='backward')
test.mat = model.matrix(Total_salary~., data=nba[test,])
val.errors=rep(NA,47)
for (i in 1:47){
  coefi=coef(regfit.best, id=i)
  pred=test.mat[,names(coefi)]%*%coefi
  val.errors[i]=sqrt(mean((nba$Total_salary[test]-pred)^2))
}
print(paste("Test Dataset Minimum RMSE:", round(min(val.errors),2)))
coef(regfit.best ,which.min(val.errors))

```



#### Linear Regression Model(all data)
```{r}
regfit.fw = lm(Total_salary~Age+Games+Games_Started+Points_Per_Game+Value_over_Replacement_Player, data=nba)
summary(regfit.fw)
```

#### Linear Regression VIF
```{r}
library(car)
vif(regfit.fw)
```


### PCA
```{r}
nba.pca <- prcomp(nba[,-c(48)], center = TRUE, scale. = TRUE)
summary(nba.pca)

biplot(nba.pca,scale=0,cex=0.4)

pr_var = nba.pca$sdev^2
prop_varex <- pr_var/sum(pr_var)

# scree plot
plot(prop_varex, xlab = "Principal Component",
             ylab = "Proportion of Variance Explained",
             type = "b")

# cumulative scree plot
plot(cumsum(prop_varex), xlab = "Principal Component",
              ylab = "Cumulative Proportion of Variance Explained",
              type = "b")
```


### PCR

```{r}
library(pls)
x = model.matrix(Total_salary~.,data=nba)[,-1]
y = nba$Total_salary
pcr.fit=pcr(Total_salary~., data=nba, subset=train, scale=TRUE, validation='CV')
summary(pcr.fit)
validationplot(pcr.fit, val.type="MSEP")
pcr.pred=predict(pcr.fit, x[test,], ncomp=17)
print(paste("Test Dataset Minimum RMSE:", round(sqrt(mean((pcr.pred-y[test])^2)),2)))
```

#### PCR(all data)
```{r}
pcr.fit=pcr(y~x, scale=TRUE, ncomp=17)
summary(pcr.fit)
predplot(pcr.fit)
```